### ISSUE TITLE
cif v2 -> v3 migration?

### ISSUE THREAD

**Issue by villain** [csirtgadgets/bearded-avenger-deploymentkit#35]
question: will be a migration script/process for those running CIF v2 in order to upgrade to v3 without having to start from scratch

**Comment by wesyoung** [comment]
dunno- it's not something that's easily generalized because everyone's environment ends up different.  that said i don't think it's that hard either if you want to test some ideas and contribute something. seems like if you were going from ES to ES and only taking high confidence data with you, it should be pretty trivial-

check out this thread and feel free to send a PR if you make some headway.

https://groups.google.com/forum/#!topic/ci-framework/lIK3aZjhhiM
