### ISSUE TITLE
Hunter is not working in this release

### ISSUE THREAD

**Issue by marekbert** [csirtgadgets/bearded-avenger-deploymentkit#7]
Hi,

I hope this is not a stupid issue, however I have installed this latest release on UBUNTU 16 using easybutton.sh and everything seems to be working fine except enrichment via hunter. I have tried to compare it with the latest version I have been using that was working fine and only thing i was able to find is that defaultly /etc/cif.env in this release looks like this:

ubuntu@ip-172-31-9-151:~$ cat /etc/cif.env
# https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html

CIF_LOGLEVEL=INFO

CIF_RUNTIME_PATH=/var/lib/cif
CIF_STORE_STORE=sqlite
CIF_ROUTER_CONFIG_PATH=/etc/cif/cif-router.yml
CIF_HUNTER_EXCLUDE=osint.bambenekconsulting.com:dga
CIF_HUNTER_THREADS=
CIF_GATHERER_GEO_FQDN=

CSIRTG_SMRT_RUNTIME_PATH=/var/lib/cif

Is it okay that hunter threads are empty ?

Thank you,

Marek

**Comment by marekbert** [comment]
If I restart the cif-router service, I am also missing "launching hunters" etc.

**Comment by marekbert** [comment]
So, I had to fill these lines.. quite obvious but I didnt expect that

**Comment by wesyoung** [comment]
in the latest default install we're leaving those blank on purpose. we've had numerous issues over the years with new users who didn't quite understand what hunters (formally cif-worker) did, and why the default install wreaked havoc on their system (network traffic, cpu utilization, as hunters churned through messages). there's still some FAQ work to be done around this specific question and the best ways to turn them back on by default..

make sense?

**Comment by marekbert** [comment]
@wesyoung  Yes, thank you. What would be your recommended settings on AWS m4.xlarge for example dedicated to CIF. I've used 8.  When I check top, the utilization isn't that full and initial processing take quite time :) Thanks for your prompt response

**Comment by wesyoung** [comment]
right now i'm testing with a t2.medium and 2-4 threads. i've done some testing with 4-8 but not enough to really know where the happy balance is. at some point the network latency as well as how fast sqlite can really upsert everything (avg i've seen is 250/sec) becomes the problem.

my best guess right now [with sqlite] is somewhere between 4-6. at some point a postgres plugin needs to be built/contributed to get past that, and / or something like reddis or elasticsearch and then you can probably start test scaling well past that limit. 

the elasticsearch plugin exists, but needs more work. postgres/reddis should be easy to build from the sqlite model.

all that said; the reality probably is; after the initial run, because smrt is now keeping track of what it's already inserted, 2-4 threads in sqlite will be sufficient for the default rulesets. if you're plowing lots of custom url feeds at the thing, that's where hunters do the most work and will probably require something more multi-threaded than sqlite.

make sense?

**Comment by marekbert** [comment]
@wesyoung Yes, absolutely. Thank you for taking time to asnwer :) 👍
